allow fast resize, move
Squashed commit of the following:

commit 2917bb47ec17e8e8c8d78558103d4d9ef80f3cea
Author: yeaminsarder <yeaminsardersr@gmail.com>
Date:   Thu Oct 16 12:07:16 2025 +0600

    Squashed commit of the following:

    commit ef316385f92d04610c8e5c8f88f53c11480d24ce
    Author: Omar <jtotheomer@gmail.com>
    Date:   Thu Oct 16 11:44:14 2025 +0600

        making resizing flexible

    commit 3243197d0a286c92e2bece71e43f1ba6fa9c1227
    Author: Omar <jtotheomer@gmail.com>
    Date:   Thu Oct 16 11:07:16 2025 +0600

        made card resizing flexible

    commit a0ae19026376c7759f12a6d5efc4bd0877db501a
    Author: Omar <jtotheomer@gmail.com>
    Date:   Wed Oct 15 21:47:15 2025 +0600

        error: mouse grab 2

    commit 9ffd5f453813f7a523aee8d4da100483ae1107c6
    Author: Omar <jtotheomer@gmail.com>
    Date:   Wed Oct 15 21:27:43 2025 +0600

        error: mouse grab